/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.neu.csye6200.view;

import edu.neu.csye6200.objects.AgeGroupEnum;
import edu.neu.csye6200.objects.ClassRoom;
import edu.neu.csye6200.services.ClassroomService;
import javax.swing.JOptionPane;

/**
 *
 * @author jasonpauldarivemula
 */
public class NewClassroomForm extends javax.swing.JFrame {

    /**
     * Creates new form NewClassroomForm
     */
    public NewClassroomForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Title = new javax.swing.JPanel();
        lbl_Logo = new javax.swing.JLabel();
        lbl_Title = new javax.swing.JLabel();
        panel_classroomform = new javax.swing.JPanel();
        jCb_agegroup = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_sectionname = new javax.swing.JTextField();
        btn_addclassroom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Logo.setText("Logo");

        lbl_Title.setText("NORTHEASTERN DAYCARE");
        lbl_Title.setToolTipText("");

        javax.swing.GroupLayout panel_TitleLayout = new javax.swing.GroupLayout(panel_Title);
        panel_Title.setLayout(panel_TitleLayout);
        panel_TitleLayout.setHorizontalGroup(
            panel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TitleLayout.createSequentialGroup()
                .addComponent(lbl_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(lbl_Title)
                .addGap(0, 200, Short.MAX_VALUE))
        );
        panel_TitleLayout.setVerticalGroup(
            panel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Title))
        );

        jCb_agegroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Age Group 1", "Age Group 2", "Age Group 3", "Age Group 4", "Age Group 5" }));
        jCb_agegroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb_agegroupActionPerformed(evt);
            }
        });

        jLabel1.setText("Age Group :");

        jLabel2.setText("Section Name : ");

        btn_addclassroom.setText("Add Classroom");
        btn_addclassroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addclassroomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_classroomformLayout = new javax.swing.GroupLayout(panel_classroomform);
        panel_classroomform.setLayout(panel_classroomformLayout);
        panel_classroomformLayout.setHorizontalGroup(
            panel_classroomformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_classroomformLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panel_classroomformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_classroomformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_sectionname)
                    .addComponent(jCb_agegroup, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_classroomformLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(btn_addclassroom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_classroomformLayout.setVerticalGroup(
            panel_classroomformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_classroomformLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panel_classroomformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCb_agegroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_classroomformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_sectionname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btn_addclassroom)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_classroomform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_classroomform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCb_agegroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb_agegroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb_agegroupActionPerformed

    private void btn_addclassroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addclassroomActionPerformed
        // TODO add your handling code here:
        String sectionName = txt_sectionname.getText();
        
        String group = (String)jCb_agegroup.getSelectedItem();
        AgeGroupEnum selectedGroup=null;
        
        for(AgeGroupEnum ageGroup : AgeGroupEnum.values())
        {
            if(group.equals(ageGroup.getAgeGroupName())){
                selectedGroup=ageGroup;
                break;
            }
        }
        int groupId = selectedGroup.getAgeGroupId();
        int groupAvailableCapacity = selectedGroup.getMaxGroupSize();
        
        ClassRoom cr = new ClassRoom(groupId,groupAvailableCapacity,sectionName);
        
        int classroomId = ClassroomService.insertClassroom(cr);
        
        if(classroomId != -1)
            JOptionPane.showMessageDialog(this, "Classroom was added succesfully.");
        else
            JOptionPane.showMessageDialog(this, "There was an error. Please try again.");
        
        this.dispose();
//        HomeFrame homeFrame = new HomeFrame();
        EditClassroomForm edcrf = new EditClassroomForm( classroomId);
        edcrf.setVisible(true);
        
    }//GEN-LAST:event_btn_addclassroomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewClassroomForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewClassroomForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewClassroomForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewClassroomForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewClassroomForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addclassroom;
    private javax.swing.JComboBox<String> jCb_agegroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JPanel panel_Title;
    private javax.swing.JPanel panel_classroomform;
    private javax.swing.JTextField txt_sectionname;
    // End of variables declaration//GEN-END:variables
}
